app:
  user:
    creation:
      authorizedCountries: "FR"
      ip:
        check:
          enabled: false
  ipapi:
    base:
      url: https://ipapi.co

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - url: ../v3/api-docs/users.openapi.yaml
        name: Users
    deepLinking: true
    defaultModelsExpandDepth: 0
    defaultModelExpandDepth: 0
    defaultModelRendering: model
    displayRequestDuration: true
    docExpansion: list
    filter:
    operationsSorter: alpha
    tagsSorter: alpha
    showExtensions: true
    supportedSubmitMethods: ["get", "put", "post", "delete", "options", "head", "patch", "trace"]
    disable-swagger-default-url: true
    validatorUrl:

database:
  name: users-management

# Only enable MongoDB transactions in a real production environment as transactions are not supported without a replica set
mongo:
  transactions:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost/test}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}

messaging:
  successfulCreatedUsersQueueName: users.creation.success
  unsuccessfulCreatedUsersQueueName: users.creation.failure
  directExchangeName: direct-exchange
  successfulCreatedUsersRoutingKey: users.creation.success
  unsuccessfulCreatedUsersRoutingKey: users.creation.failure
